### ISSUE TITLE
Add Future section to docs

### ISSUE THREAD

**Issue by HaydenSansum** [fire-breathing-rubber-lemons/cs207-FinalProject#51]

**Comment by HaydenSansum** [comment]
Ideas:

* Optimization
* Extend graph/learning mode to be more functional
* Dual numbers implementation

**Comment by catharinewu** [comment]
https://github.com/cs207FinalProjectGroup/cs207-FinalProject/blob/master/docs/documentation.ipynb

**Comment by HaydenSansum** [comment]
Built on top of numpy as already parallelizable
